version: '3'
services:
  blockchain:
    image: trufflesuite/ganache-cli:latest
    ports:
      - '8545:8545'
  betting:
    image: jeopardy/betting
    build: ./services/betting
    depends_on:
      blockchain:
        condition: service_started
    ports:
      - '8000:8000'
  