FROM node:16-alpine3.14

WORKDIR /urs/src/app

# add `/app/node_modules/.bin` to $PATH
RUN apk update && apk upgrade && apk add --update alpine-sdk && \
    apk add --no-cache bash git openssh make cmake 
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
#ENV PYTHON /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
#RUN apt-get install python -y

COPY package*.json ./
#COPY package-lock.json ./
COPY ./.env ./
#COPY truffle-config.js ./
RUN npm install 

ENV PATH /usr/src/app/node_modules/.bin:$PATH

# add app
COPY . .
#RUN npm install -g ganache-cli
#RUN truffle deploy
EXPOSE 8000

# start app
CMD ["node", "index.js"]