FROM node:16-alpine3.14

WORKDIR /urs/src/app
COPY package*.json ./
COPY ./.env ./
#COPY truffle-config.js ./
RUN npm install 

ENV PATH /usr/src/app/node_modules/.bin:$PATH

# add app
COPY . .
#RUN npm install -g ganache-cli
#RUN truffle deploy
EXPOSE 8000

# start app
CMD ["node", "./src/index.js"]